export const plantInformation = [
    {
        imgUrl: '/Acer.jpg',
        imgTreeUrl: '/AcerTree.jpg',
        name: 'Acer',
        description: 'Acer or Maple trees are a firm favourite because of their distinctive leaf shapes and vibrant foliage that change colour through the seasons on many varieties. Colours include purple, red, orange, yellow, pink and green. There are over 65 varieties of Acer tree, including many varieties of Japanese Maple, Norway Maple, Field Maple and some more unusual choices.',
    },
    {
        imgUrl: '/AlnusIncana.jpg',
        imgTreeUrl: '/AlnusIncanaTree.jpg',
        name: 'Alnus Insana',
        description: 'Alnus incana, the grey alder or speckled alder, is a species of multi-stemmed, shrubby tree in the birch family, with a wide range across the cooler parts of the Northern Hemisphere. Tolerant of wetter soils, they can be a common sight in swamps and wetlands. It is easily distinguished by its small cones, speckled bark and broad leaves.',
    },
    {
        imgUrl: '/BetulaPubescens.jpg',
        imgTreeUrl: '/BetulaPubescensTree.jpg',
        name: 'Betula Pubescens',
        description: 'Betula pubescens, commonly known as downy birch and also as moor birch, white birch, European white birch or hairy birch, is a species of deciduous tree, native and abundant throughout northern Europe and northern Asia, growing farther north than any other broadleaf tree.',
    },
    {
        imgUrl: '/FagusSilvatica.jpg',
        imgTreeUrl: '/FagusSylvaticaTree.jpg',
        name: 'Fagus Sylvatica',
        description: 'Fagus sylvatica, the European beech or common beech,  is a large tree, capable of reaching heights of up to 50 metres. The leaves of beech are often not abscissed (dropped) in the autumn and instead remain on the tree until the spring.',
    },
    {
        imgUrl: '/Populus.jpg',
        imgTreeUrl: '/PopulusTree.jpg',
        name: 'Populus',
        description: 'Populus is a genus of 25–30 species of deciduous flowering plants in the family Salicaceae, native to most of the Northern Hemisphere. English names variously applied to different species include poplar, aspen, and cottonwood.',
    },
    {
        imgUrl: '/PopulusTremula.jpg',
        imgTreeUrl: '/PopulusTremulaTree.jpg',
        name: 'Populus Tremula',
        description: 'Also known as quaking aspen, this is a beautiful tree with shimmering foliage. Mature trees grow to 25m. Older trees may be covered with lichen, which gives the trunk a black appearance, and the bark is grey and often pitted with diamond-shaped pores, called lenticels. The uppermost branches are sometimes bent over horizontally.',
    },
    {
        imgUrl: '/Quercus.jpg',
        imgTreeUrl: '/QuercusTreeTree.jpg',
        name: 'Quercus',
        description: 'A large, deciduous tree growing up to 20–40m tall. Also known as common oak, this species grows and matures to form a broad and spreading crown with sturdy branches beneath.',
    },
    {
        imgUrl: '/SalixAlbaSericea.jpg',
        imgTreeUrl: '/SalixAlbaSericeaTree.jpg',
        name: 'Salix Alba Sericea',
        description: 'Salix alba, the white willow, is a species of willow native to Europe and western and central Asia. The name derives from the white tone to the undersides of the leaves.\nIt is a medium-sized to large deciduous tree growing up to 10–30 m tall, with a trunk up to 1 m diameter and an irregular, often-leaning crown. ',
    },
    {
        imgUrl: '/SalixAurita.jpg',
        imgTreeUrl: '/SalixAuritaTree.jpg',
        name: 'Salix Aurita',
        description: 'Salix aurita, the eared willow, is a species of willow distributed over much of Europe, and occasionally cultivated. It is a shrub to 2.5 m in height, distinguished from the similar but slightly larger Salix cinerea by its reddish petioles and young twigs. It was named for its persistent kidney-shaped stipules along the shoots.',
    },
    {
        imgUrl: '/SalixCinerea.jpg',
        imgTreeUrl: '/SalixCinereaTree.jpg',
        name: 'Salix Cinerea',
        description: 'Grey willow grows in woodland and hedgerows, as well as in damp areas, such as near canals, rivers and streams. It is native to Europe and western Asia',
    },
    {
        imgUrl: '/SorbusAucuparia.jpg',
        imgTreeUrl: '/SorbusAucupariaTree.jpg',
        name: 'Sorbus Aucuparia',
        description: 'This tree occurs naturally in practically the whole of Europe. It has a broad ovoid crown. In its early years the crown is fairly narrow but broadens out later. Because of its abundant fruit the branches bend, eventually making the crown almost rounded. The smooth trunk is light grey and flakes off somewhat at a later stage.',
    },
    {
        imgUrl: '/SorbusIntermedia.jpg',
        imgTreeUrl: '/SorbusIntermediaTree.jpg',
        name: 'Sorbus Intermedia',
        description: 'Scandosorbus intermedia, the Swedish whitebeam is a species of whitebeam found in southern Sweden, with scattered occurrences in easternmost Denmark (Bornholm), the far southwest of Finland, Estonia, Latvia and northern Poland. The leaves are green above, and densely hairy with pale grey-white hairs beneath.',
    },
    {
        imgUrl: '/Tilia.jpg',
        imgTreeUrl: '/TiliaTree.jpg',
        name: 'Tilia',
        description: 'Tilia is a native throughout most of the temperate Northern Hemisphere. The tree is known as linden for the European species, but in Britain and Ireland they are commonly called lime trees, although they are not related to the citrus lime. Tilia species are mostly large, deciduous trees, reaching typically 20 to 40 m.',
    },
    {
        imgUrl: '/UlmusCarpinifolia.jpg',
        imgTreeUrl: '/UlmusCarpinifoliaTree.jpg',
        name: 'Ulmus Carpinifolia',
        description: 'Ulmus Carpinifolia - the field elm, is by far the most polymorphic of the European species. Its natural range is predominantly south European. The tree\'s typical habitat is low-lying forest along the main rivers, growing in association with oak and ash, where it tolerates summer floods as well as droughts.',
    },
    {
        imgUrl: '/UlmusGlabra.jpg',
        imgTreeUrl: '/UlmusGlabraTree.jpg',
        name: 'Ulmus Glabra',
        description: 'Wych elm (Ulmus glabra) is a large deciduous tree with a widespread natural range, including most of Europe, from the United Kingdom to Siberia, including Asia Minor.\nThe tree was previously widely planted as an ornamental in urban parks and along roadsides but is no longer used as such due to its susceptibility to Dutch elm disease.',
    },
]